news api,  point's  4.1 - 4.3 done
Artofpaganini/NewsApi-Task-4-Dobrov- pull request #1
Opened 2020-09-26 15:10 UTC by Artofpaganini

1.	Источник данных https://newsapi.org/ С помощью библиотеки Retrofit2 и GET запросов разработать возможность получения информации о новостях по заданным критериям. DONE
2.	Вывод новостей должен осуществляться в виде RecyclerView. DONE
Объем новостей должен быть ограничен 20. DONE
Тема хардкодится (q=software), дата - текущий день календаря. DONE
В тулбаре заголовок Software. DONE
Элементы списка RecyclerView должны содержать в себе три TextView: author, title и publishedAt.  DONE
При клике на элемент должна открываться другая Activity с информацией title, source:name и description.   DONE
3.	Реализовать механизм Pull-to-Refresh, при котором обновляется список новостей в случае свайпа сверху вниз.  DONE
Во время данного обновления должен отображаться диалог загрузки, который должен скрываться только по окончании загрузки или же ошибки. В случае ошибки должен отображать диалог с соответствующим текстом (текст произволен, важна суть).   DONE

2020-09-28 07:24 UTC, Akvit requested changes

2020-09-28 07:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/DetailActivity.java
> +        dataNewsDetails.setUrl(intent.getStringExtra("url"));
- [ ] константы

2020-09-28 07:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/MainActivity.java
> +    public void loadJson(String keyword) {
- [ ] аннотация

- [ ] приватный метод

2020-09-28 07:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/MainActivity.java
> +                intent.putExtra("url", article.getUrl());
- [ ] сделай Article Parcelable

2020-09-28 07:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/MainActivity.java
> +    private void onLoadingSwipeRefresh(final String keyword) {
- [ ] аннотация

2020-09-28 07:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/MainActivity.java
> +                new Runnable() {
- [ ] лямбда

2020-09-28 07:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/adapter/MyAdapter.java
> +    private OnItemClickListener onItemClickListener;
у тебя лисенер один для всех элементов
- [ ] убери отсюда

2020-09-28 07:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/adapter/MyAdapter.java
> +    private Context context;
- [ ] контекст здесь не нужен

2020-09-28 07:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/adapter/MyAdapter.java
> +        TextView title;
- [ ] приватные поля

2020-09-28 07:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/adapter/MyAdapter.java
> +        private void bind(int position) {
Почему ты просто не передаёшь сюда модель?

2020-09-28 07:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/models/Article.java
> +    public void setContent(String content) {
- [ ] аннотации @nullable/@nonnull

2020-09-28 07:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/models/News.java
> +    public void setStatus(String status) {
- [ ] то же самое

2020-09-28 07:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/models/Source.java
> +    public void setId(String id) {
- [ ] то же самое

2020-09-28 07:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/util/Utils.java
> +
- [ ] в утилитных классах делают приватный конструктор и бросают illegalStateException

2020-09-28 07:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/util/Utils.java
> +    public static String DateFormat(String oldStringDate){
- [ ] название метода с маленькой

2020-09-28 07:24 UTC, Akvit commented on app/src/main/res/layout/activity_news_detail.xml
> +        app:layout_constraintHorizontal_bias="0.0"
- [ ] bias="0.0"
bias="0.004" лишнее

2020-09-28 07:32 UTC, Artofpaganini commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/util/DataNewsDetails.java
> +package by.andersen.intern.dobrov.mynewsapi.util;
не совсем понял, что ты тут  имеешь  ввиду???

2020-09-28 15:24 UTC, Akvit requested changes

2020-09-28 15:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/adapter/MyAdapter.java
> +        private TextView published_at;
- [ ] не правильный стиль у переменной published_at

2020-09-28 15:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/MainActivity.java
> +        ApiInterface apiInterface = ApiClient.getApiClient().create(ApiInterface.class);
те, ты создаёшь апи каждый раз, когда свайпаешь экран? Это лишняя нагрузка на устройство

- [ ] апи не должен пересоздаваться

2020-09-28 15:24 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/MainActivity.java
> +    private void getCategoryFromSpinner(@NonNull Spinner spinner) {
- [ ] у тебя и так есть спиннер в поле

2020-09-29 05:47 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/util/DataNewsDetails.java
> +package by.andersen.intern.dobrov.mynewsapi.util;
это ниразу не утилитный класс. почему он находится в папке util?

2020-09-29 06:43 UTC, merged