Feature/mvvm
Artofpaganini/NewsApi-Task-4-Dobrov- pull request #5
Opened 2020-10-13 08:48 UTC by Artofpaganini

Переписать приложение News Service (Разработанное в задании к Теме 4) с использованием RxPM и Architecture Components

2020-10-13 19:31 UTC, Akvit requested changes

2020-10-13 19:31 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModel.java
> +public class NewsListViewModel extends AndroidViewModel implements NewListViewModelInterface {
обычно для вм никто интерфейсов не пишет

2020-10-13 19:31 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModel.java
> +import by.andersen.intern.dobrov.mynewsapi.model.Article;
- [ ] сквош!!!! ну сколько можно

2020-10-13 21:39 UTC, Akvit requested changes

2020-10-14 06:46 UTC, Artofpaganini commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModel.java
> +public class NewsListViewModel extends AndroidViewModel implements NewListViewModelInterface {
убрал)

2020-10-14 06:46 UTC, Artofpaganini commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModel.java
> +import by.andersen.intern.dobrov.mynewsapi.model.Article;
сейчас все исправлю  и  сделаю ))

2020-10-15 14:49 UTC, Akvit requested changes

2020-10-15 14:49 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/repository/ConnectionRepository.java
> +    private static NewsDatabase newsDatabase;
- [ ] убери live data

2020-10-15 14:49 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/repository/ConnectionRepository.java
> +    private Application application;
- [ ] у тебя аппликейшен только в конструкотре используется. Зачем он тут? Только память занимает

2020-10-15 14:49 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/repository/ConnectionRepository.java
> +        Log.d(TAG, "getError: CALL GET ERROR FROM MODEL");
ошибки выводятся через метод e обычно. Настаивать на изменении не буду

2020-10-15 14:49 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/repository/ConnectionRepository.java
>          apiFactory = ApiFactory.getInstance();
- [ ] у тебя фабрика должна создаваться только единожды, а не при каждом вызове loadData(). Его создание может потенциально занимать больших ресурсов

2020-10-18 12:49 UTC, Akvit requested changes

2020-10-18 12:49 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModel.java
> +
- [ ] лишний отступ

2020-10-18 12:49 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModel.java
> +
- [ ] лишний отступ

2020-10-18 12:49 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModel.java
> +
- [ ] RemoteData не может общаться с view model, а только с репозиторием

2020-10-18 12:49 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModel.java
> +    private final MutableLiveData<List<Article>> articlesForView = new MutableLiveData<>();
Не вижу где тут у тебя сохраняются данные на время поворота экрана

- [ ] сохранение и переиспользование данных при повороте

2020-10-18 12:49 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/repository/remote/RemoteData.java
> +    private final LocalData localData;
Локал дата - не часть ремоут даты. Это инструменты для репозтория. И эти инструменты ничего не должны знать друг о друге

- [ ] убери отсюда LocalData

2020-10-19 06:37 UTC, Artofpaganini commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/NewsListActivity.java
> +                viewModel.clearError();
я так сделал что бы   первый раз  ошибка  показывалась  а при повороте экрана к примеру ее уже не было, но если так не нужно то я  уберу

2020-10-19 10:37 UTC, Akvit requested changes

2020-10-19 10:37 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModel.java
> +
- [ ] лишний отступ

2020-10-19 10:37 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModel.java
> +
- [ ] лишний отступ

2020-10-19 10:37 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModel.java
> +
- [ ] лишний отступ

2020-10-19 10:37 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModel.java
> +        error.setValue(null);
не понятно зачем тебе ошибку чистить. у тебя ж там тоаст обычный

- [ ] убери

2020-10-19 10:46 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/NewsListActivity.java
> +                viewModel.clearError();
это костыль

2020-10-21 19:27 UTC, Akvit requested changes

2020-10-21 19:27 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModel.java
> +    private MutableLiveData<List<Article>> oldData;
- [ ] у тебя должна быть одна live data, которая, исходя из ситуации, стучится в разные источники

2020-10-21 19:27 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/repository/ConnectionRepository.java
> +            remoteData.requestNews(keyword);
Почему ты тут берёшь данные и из сети, и из бд?

- [ ] убери

2020-10-21 19:27 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/repository/remote/RemoteData.java
> +    private void putDataFromNetworkToDbAndInitDataFromDbWithFormatDate(@NonNull List<Article> articles) {
Помнишь про принцип разделения ответственности? Почему класс, который занимается сетью что-то делает с бд?

- [ ] сделай нормально

2020-10-21 19:27 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/repository/remote/RemoteData.java
> +                if (errorCounter > 1) {
Если число ошибок больше одного, то говорим репозиторию, что ошибок нет, иначе говорим...Не совсем очевидная логика, да и по статику связываться - плохая идея

2020-10-21 19:27 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/repository/ConnectionRepository.java
> +    private static LocalData localData;
- [ ] в данном случае, статики - зло. Убери их

2020-10-21 19:27 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/GlideBindingAdapter.java
> +public class GlideBindingAdapter {
- [ ] GlideDataBindingAdapter

2020-10-21 19:27 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/repository/local/LocalData.java
> +    private static NewsDatabase newsDatabase;
- [ ] db не статик

2020-10-22 19:01 UTC, Akvit requested changes

2020-10-23 06:05 UTC, Artofpaganini commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/repository/ConnectionRepository.java
не совсем понял что имеется ввиду??

2020-10-23 06:12 UTC, Artofpaganini commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModel.java
> +        if (requestArticles == null || !(keyword.equals(intermediateKeyword))) {
я пробовал  ,   используя доки с оф  сайта
https://developer.android.com/topic/libraries/architecture/viewmodel
+  добавил проверку на само слово которое приходит ,  т.к. у меня спинер, и слова меняются, был вариант сделать через  boolean   но  мне он показался более запутанным, поэтому  я думаю что  проще сделать уже нельзя)

2020-10-24 17:25 UTC, Akvit requested changes

2020-10-24 17:25 UTC, Akvit commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.READ_CONTACTS" />
- [ ] А это зачем??

2020-10-24 17:58 UTC, Akvit requested changes

2020-10-24 17:58 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/repository/local/LocalData.java
> +        newsDatabase = NewsDatabase.getInstance(application);
когда возьмёшь даггер, будешь передавать датабазу в конструктор и геттер надо будет убрать

2020-10-24 17:58 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/repository/local/LocalData.java
> +    private static int rowsCounter;
- [ ] это не статик

2020-10-24 17:58 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/repository/local/LocalData.java
> +    public ConnectionRepository getConnectionRepository() {
можно удалить

2020-10-24 17:58 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/util/RequestParameters.java
> +    public static boolean isOnline(Context context) {
один и тот же метод используется как в сетевом, так и презентационном слое. пока прощаю

2020-10-24 18:05 UTC, Akvit requested changes

2020-10-24 18:05 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModelTest.java
> +        newsListViewModel = null;
- [ ] лишний код, на самом деле. Ты же всё равно пересоздашь

2020-10-24 18:05 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/repository/local/LocalDataTest.java
> +        Context context = ApplicationProvider.getApplicationContext();
- [ ] mock

2020-10-24 18:05 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/repository/remote/RemoteDataTest.java
> +    public final String API_KEY = "59f165be02ad40e2ba19b7347c289ad0";
- [ ] статик

2020-10-24 18:05 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/repository/remote/RemoteDataTest.java
> +    private RemoteData remoteData;
- [ ] это к своим нестатичным братьям

2020-10-24 18:05 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/repository/remote/RemoteDataTest.java
> +    private Call<News> mockCall;
- [ ] ты не замокал это поле и передаёшь его куда-то

2020-10-24 18:05 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/repository/remote/RemoteDataTest.java
> +        when(apiInterface.getNewsByCategory(KEYWORD, LANGUAGE, SORT_BY, API_KEY)).thenReturn(mockCall);
ты здесь ничего не тестируешь

2020-10-25 08:35 UTC, Artofpaganini commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/repository/local/LocalData.java
> +        newsDatabase = NewsDatabase.getInstance(application);
да я в курсе)) я уже ег о изучаю  потихоньку ^^

2020-10-26 09:30 UTC, Akvit requested changes

2020-10-26 09:30 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModelTest.java
> +        context = getApplicationContext();
- [ ] окей. а теперь удали эту строку и сделай эту ссылку типа application

2020-10-26 09:30 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/repository/local/LocalDataTest.java
> +        context = ApplicationProvider.getApplicationContext();
- [ ] то же самое

2020-10-26 09:30 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/repository/remote/RemoteDataTest.java
> +    private RemoteData remoteData;
в смысле перемести это к мокам. Статики отдельно, не статики отдельно

2020-10-26 09:30 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/repository/remote/RemoteDataTest.java
> +    private Call<News> mockCall;
а теперь эта переменная нигде не используется

2020-10-26 10:08 UTC, Akvit requested changes

2020-10-26 10:08 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/activity/viewmodel/NewsListViewModelTest.java
> +//        newsListViewModel = new NewsListViewModel((Application) context);
- [ ] комменты убери

2020-10-26 10:08 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/repository/local/LocalDataTest.java
> +        database = Room.inMemoryDatabaseBuilder(context, NewsDatabase.class).build();
сюда можно было передавать мок апликейшена

2020-10-26 10:41 UTC, merged