10.4Используя Dagger2, внедрить через @Inject зависимость в активити/фрагмент от библиотеки загрузки изображений (Glide или Picasso) и Retrofit там, где они непосредственно используются, а также Presenter/ViewModel (на выбор).
Artofpaganini/NewsApi-Task-4-Dobrov- pull request #7
Opened 2020-10-31 11:03 UTC by Artofpaganini

10.4Используя Dagger2, внедрить через @Inject зависимость в активити/фрагмент от библиотеки загрузки изображений (Glide или Picasso) и Retrofit там, где они непосредственно используются, а также Presenter/ViewModel (на выбор).

2020-11-01 07:51 UTC, Akvit requested changes

2020-11-01 07:51 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/data/local/LocalDataImpl.java
>          return newsDatabase;
- [ ] ты и так этот метод внутри класса используешь. так что удали и пользуйся переменной

2020-11-01 07:51 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/data/local/LocalDataImpl.java
> +    private NewsDAO newsDAO;
почему newsDAO не используется?

2020-11-01 07:51 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/di/AppComponent.java
> +                NewsListViewModelModule.class,
- [ ] в активити компонент

2020-11-01 07:51 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/di/AppComponent.java
> +                AdapterModule.class
- [ ] в активити компонент

2020-11-01 07:51 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/presentation/list/NewsListActivity.java
> +    NewsListViewModelFactory newsListViewModelFactory;
- [ ] создавай в даггер модуле вм, а не фабрику

2020-11-01 07:51 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/presentation/list/NewsListActivity.java
> +    private GlobalOnlineCheck globalOnlineCheck;
- [ ] не используется

2020-11-01 09:22 UTC, Artofpaganini commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/presentation/list/NewsListActivity.java
> +    private GlobalOnlineCheck globalOnlineCheck;
я иничу тут это поле что бы получить  аппликейшн  который испольует активити

2020-11-02 13:56 UTC, Akvit requested changes

2020-11-02 13:56 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/di/modules/NewsListViewModelModule.java
> +            }
можно было объединить с провайдом ресайклера

2020-11-02 13:56 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/presentation/list/adapter/RecyclerViewAdapter.java
> +    public RecyclerViewAdapter() {
- [ ] Это лишнее

2020-11-03 11:27 UTC, Akvit requested changes

2020-11-03 11:27 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/mynewsapi/presentation/list/NewsListActivity.java
> +    NewsListViewModel viewModel;
- [ ] private

2020-11-03 11:57 UTC, merged