10.6Написать Unit-тесты на основной функционал Domain и Data слоев приложения.
Artofpaganini/NewsApi-Task-4-Dobrov- pull request #9
Opened 2020-11-06 13:55 UTC by Artofpaganini

10.6Написать Unit-тесты на основной функционал Domain и Data слоев приложения.

2020-11-09 06:27 UTC, Akvit requested changes

2020-11-09 06:27 UTC, Akvit commented on app/src/androidTest/java/by/andersen/intern/dobrov/mynewsapi/TestUtilConst.java
> +    public static final Article ARTICLE_1 = new Article(new Source(), "Some Author", "Some title",
и что ты тут тестируешь?

2020-11-09 06:27 UTC, Akvit commented on gradle.properties
> +org.gradle.daemon=true
а это для чего?

2020-11-09 06:27 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/data/remote/RemoteDataImplTest.java
> +
не вижу тестов на
LocalDataImpl
RemoteDataImpl
ConnectionRepositoryImpl
ArticlesMapperImpl
ConverterMapper

2020-11-09 06:30 UTC, Artofpaganini commented on gradle.properties
> +org.gradle.daemon=true
поставил оффлайн  мод чтобы  градл   билдился быстрее , оптимизация  студии

2020-11-09 06:30 UTC, Artofpaganini commented on app/src/androidTest/java/by/andersen/intern/dobrov/mynewsapi/TestUtilConst.java
> +    public static final Article ARTICLE_1 = new Article(new Source(), "Some Author", "Some title",
ну это  константы  для  тестирования

2020-11-10 08:18 UTC, Akvit commented on gradle.properties
> +org.gradle.daemon=true
![image](https://user-images.githubusercontent.com/17576565/98647791-6f7bcf80-2346-11eb-9d9b-a506f02eb5a3.png)

2020-11-10 08:26 UTC, Akvit requested changes

2020-11-10 08:26 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/data/local/LocalDataImplTest.java
> +    private NewsDatabase newsDatabase;
- [ ] Mock

2020-11-10 08:26 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/data/local/LocalDataImplTest.java
> +    private List<Article> articles;
- [ ] это мокать не надо

2020-11-10 08:26 UTC, Akvit commented on app/src/test/java/by/andersen/intern/dobrov/mynewsapi/data/remote/RemoteDataImplTest.java
> +    private ApiInterface apiInterface;
- [ ] Mock

2020-11-10 13:38 UTC, merged